# Generated by Django 3.1 on 2020-08-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('ques_no', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=300)),
                ('opt1', models.CharField(max_length=100)),
                ('opt3', models.CharField(max_length=100)),
                ('opt4', models.CharField(max_length=100)),
                ('opt5', models.CharField(max_length=100)),
                ('crt_Ans', models.CharField(max_length=100)),
            ],
        ),
    ]
