# Generated by Django 3.1 on 2020-08-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='opt5',
            new_name='opt2',
        ),
    ]
