# Generated by Django 3.1 on 2020-08-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_App', '0002_auto_20200825_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='crt_Ans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opt1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opt2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opt3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='opt4',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
