# Generated by Django 3.1 on 2020-08-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_App', '0003_auto_20200825_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans1', models.CharField(max_length=300)),
                ('ans2', models.CharField(max_length=300)),
                ('ans3', models.CharField(max_length=300)),
                ('ans4', models.CharField(max_length=300)),
            ],
        ),
    ]
