# Generated by Django 3.1 on 2020-08-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trivia_App', '0004_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='ans1',
            new_name='ans',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='ans2',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='ans3',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='ans4',
        ),
    ]
